version: '3'
services:
  radiant-electrumx:
    build:
      context: ./
    container_name: radiant-electrumx
    depends_on:
      - radiantnode
    image: radiant-electrumx
    environment:
      - DAEMON_URL=http://raduser:radpass@radiantnode:7332
      - COIN=Radiant
      - NET=mainnet
      - REQUEST_TIMEOUT=60
      - DB_DIRECTORY=/data
      - DB_ENGINE=leveldb
      - SERVICES=tcp://0.0.0.0:50010
      - REPORT_SERVICES=tcp://${DOMAIN}:50010
    ports:
      - "50010:50010"
    networks:
      - rxd-electrumx-network
    volumes:
      - ./data/electrumx:/data
    restart: always
  radiantnode:
    image: 'radiantcommunity/radiant-node:latest'
    container_name: radiantnode
    # ports:
    #   # change to 18333 if running testnet
    #   - '7333:7333'
    #   # JSON-RPC
    #   - '7332:7332'
    #   # ZMQ
    #   - '27332:27332'
    networks:
      - rxd-electrumx-network
    volumes:
      - ./data/radiant:/data
      - ./radiant.conf:/data/radiantnode/radiant.conf
    command: radiantd
    restart: always
networks:
  rxd-electrumx-network: